import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// I need a piece of state that controls whether the User is logged in or not
// I need the whole app to have access to this state so I was thinking it would go in here
// That way the state of loggedIn persists regardless of what route the user is on

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="flex">
            <Header />
          </header>
          <main>{children}</main>
          <footer>footer</footer>
        </Providers>
      </body>
    </html>
  );
}
